server:
  port: 8081
spring:
  application:
    name: tancheng
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tancheng?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen2.5:7b
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      database: 0
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段


mybatis-plus:
  type-aliases-package: com.tancheng.entity # 别名扫描包
logging:
  level:
    com.tancheng: debug
    org.springframework.ai: DEBUG
    com.tancheng.mapper: DEBUG