---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by FuFu.
--- DateTime: 2025/3/7 14:34
---
-- 获取锁中线程标识
local id = redis.call('get', KEYS[1])
-- 比较
if (id == ARGV[1]) then
    -- 释放锁
    redis.call('del', KEYS[1])
end
return 0