---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by FuFu.
--- DateTime: 2025/3/10 15:54
---
-- 1. 获取参数
local voucherId = ARGV[1]
-- 用户id
local userId = ARGV[2]
-- 订单id
local orderId = ARGV[3]
-- key
local stockKey = "seckill:stock:" .. voucherId
local orderKey = "seckill:order:" .. voucherId

-- 业务
-- 2. 判断是否有库存
if(tonumber(redis.call("get", stockKey)) <= 0) then
    return 1
end
-- 用户是否已经下单
if(redis.call("SISMEMBER", orderKey, userId) == 1) then
    return 2
end
-- 3. 减库存
redis.call("incrby", stockKey, -1)
-- 4. 下单
redis.call("sadd", orderKey, userId)

-- 发送消息到stream中, XADD stream.orders * k1 v1 k2 v2
redis.call("XADD", "stream.orders", "*", "userId", userId, "voucherId", voucherId, "id", orderId)
return 0